### ISSUE TITLE
how does copy paste work

### ISSUE THREAD

**Issue by Tanzin01** [LinuxDroidMaster/Termux-Desktops#12]
Trying to copy a line in terminal  with ctrl c but not working.

**Comment by LinuxDroidMaster** [comment]
If you are in Termux (not in any graphical desktop) copy paste is with the touchscreen. You need to select a text like in any other app and then hold the finger and copy or paste. That's why I would recommend using some desktop with Termux X11 so you can do control c and control v (take into account that in a linux terminal you should do control shift c and contorl shift v to copy paste)
