### ISSUE TITLE
Failed to execute default web browser. Input/output error.

### ISSUE THREAD

**Issue by caksup** [LinuxDroidMaster/Termux-Desktops#5]
How to solve it?

**Comment by LinuxDroidMaster** [comment]
Can you add some more info? Which browser did you installed, which desktop, how are you trying to open the browser? Probably its because you need to configure a default browser or if it is chromium you need to use the --no-sandbox option. Take a look here: https://www.youtube.com/watch?v=rDHyPw_7ETs

**Comment by Tanzin01** [comment]
Hey, just for clarification. Your text meant- no  default browser, so install one. Right?
